PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?act ?label ?publicationDate ?documentDate ?type
WHERE {
  ?act a eli:LegalResource .
  OPTIONAL { ?act rdfs:label ?label . }
  OPTIONAL { ?act eli:date_publication ?publicationDate . }
  OPTIONAL { ?act eli:date_document ?documentDate . }
  OPTIONAL { ?act eli:type_document ?type . }
}
ORDER BY ?publicationDate ?act
